export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const FETCH_PROJECT = "FETCH_PROJECT";
export const CLEAR_STATE = "CLEAR_STATE";